// Renames the objects VRChat's SPS bake leaves behind so a converted
// avatar reads as YAPS in the hierarchy rather than as somebody else's
// system with a deform bolted on.
//
// ONLY the objects that bake GENERATES. A user's own object called "SPS
// Plug" is their name for their thing and stays theirs.
//
// WHAT IS DELIBERATELY NOT RENAMED, and this is the whole reason the file
// is short: the pointer TYPE strings and the marker light RANGES. Those
// are not names, they are the wire, they are how a plug belonging to
// somebody who has never heard of this tool finds a socket on an avatar
// that came through it. Renaming SPSLL_Socket_Root to something prettier
// would make every DPS, TPS and SPS plug on the platform blind to this
// avatar, which is the exact compatibility the rename is supposed to be
// decorating. Parameters are left alone too: ChilloutVR's profiles
// restore saved values by parameter NAME, so renaming a synced one
// silently empties everybody's saved settings.
//
// The hazard here is entirely in the REPATHING. An animation clip
// addresses an object by path, so renaming a socket moves every
// descendant path with it, including the curves that switch that
// socket's marker lights on, which are the thing a whole day went into
// making work. A missed path does not error; the toggle simply stops.
// Hence: rewrite by PREFIX, not by exact match, and sweep afterwards to
// prove every path a clip still names actually resolves.

#if VRC_SDK_VRCSDK3 && CVR_CCK_EXISTS
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace AvatarBridge
{
    public static class YapsRename
    {
        const string Category = "YAPS";

        // Generated by the bake, so ours to name. Ordered longest-first is
        // not needed, these do not contain one another.
        static readonly (string From, string To)[] Names =
        {
            ("BakedSpsPlug", "YAPS Plug"),
            ("BakedSpsSocket", "YAPS Socket"),
            ("SpsAutoDistance", "YAPS Auto Distance"),
        };

        public static void Run(BridgeContext ctx)
        {
            if (!ctx.Settings.convertYapsSystems || ctx.MergedController == null)
            {
                return;
            }

            // Old path -> new path, for every object about to be renamed.
            // Collected BEFORE anything moves, because a path is only
            // readable while the hierarchy still matches it.
            var remap = new Dictionary<string, string>();
            var doomed = new List<(Transform Target, string To)>();

            foreach (var transform in ctx.Target.GetComponentsInChildren<Transform>(true))
            {
                if (transform == null)
                {
                    continue;
                }
                foreach (var (from, to) in Names)
                {
                    if (transform.name != from)
                    {
                        continue;
                    }
                    // A sibling already wearing the new name would make two
                    // objects share a path, and a shared path is a curve
                    // that drives whichever Unity finds first.
                    if (transform.parent != null
                        && Enumerable.Range(0, transform.parent.childCount)
                            .Select(i => transform.parent.GetChild(i))
                            .Any(c => c != transform && c.name == to))
                    {
                        ctx.Report.Warning(Category,
                            $"Left \"{from}\" named as it was",
                            $"Renaming it to \"{to}\" would have given it the same name as a " +
                            "object beside it, and two objects sharing a path means an animation " +
                            "reaches whichever one Unity happens to find first. Cosmetic only — " +
                            "nothing about the deform depends on the name.");
                        continue;
                    }
                    remap[ctx.PathInTarget(transform)] = ParentPath(ctx, transform) + to;
                    doomed.Add((transform, to));
                }
            }

            if (doomed.Count == 0)
            {
                return;
            }

            // A renamed object under a renamed object: its new path runs
            // through its parent's NEW name. Shortest first, so a parent is
            // settled before any child looks it up.
            foreach (string key in remap.Keys.OrderBy(k => k.Length).ToList())
            {
                string value = remap[key];
                int cut = value.LastIndexOf('/');
                if (cut < 0)
                {
                    continue;
                }
                if (Remap(value.Substring(0, cut), remap, out string movedParent))
                {
                    remap[key] = movedParent + value.Substring(cut);
                }
            }

            // Paths already dead before anything moves. An earlier pass
            // removed their object on purpose, so they are not this
            // pass's failure and not its warning.
            var deadBefore = new HashSet<string>();
            foreach (string path in AnimatedPaths(ctx))
            {
                if (Remap(path, remap, out string moved)
                    && BridgeContext.FindByAnimationPath(ctx.Target.transform, path) == null)
                {
                    deadBefore.Add(moved);
                }
            }

            foreach (var (target, to) in doomed)
            {
                target.name = to;
            }

            int rewritten = RewriteClips(ctx, remap);
            RewriteMasks(ctx, remap);
            var unresolved = Unresolved(ctx, deadBefore);

            if (unresolved.Count > 0)
            {
                // Loud, because the failure is invisible in game until
                // somebody notices a toggle doing nothing. And NAMED: a
                // count alone once fired at 86 on a real avatar and left
                // nothing to diagnose from, because the paths were counted
                // and thrown away, the check had the evidence in hand and
                // discarded it.
                var sample = unresolved.Take(12).ToList();
                ctx.Report.Warning(Category,
                    $"{unresolved.Count} animation path(s) no longer point at anything",
                    "Objects were renamed to read as YAPS and the animations addressing them were " +
                    "rewritten to match, but some now name a path this avatar does not have. " +
                    "Anything they drove will not move. Please report this at the AvatarBridge " +
                    "repo — it is a bug in the rename, not in your avatar. The first few:\n  " +
                    string.Join("\n  ", sample) +
                    (unresolved.Count > sample.Count ? $"\n  … and {unresolved.Count - sample.Count} more" : ""));
            }

            ctx.Report.Converted(Category,
                $"Renamed {doomed.Count} object(s) to YAPS",
                $"The objects VRChat's bake leaves behind are named after ITS system, so a " +
                $"converted avatar read as someone else's plumbing with a deform attached. They " +
                $"are now named for the one actually driving them. {rewritten} animation " +
                "path(s) were rewritten to follow. Nothing that another player's content reads " +
                "was touched: the contact tags and the marker light ranges are how DPS, TPS and " +
                "SPS plugs find these sockets, so they stay exactly as they were.");
        }

        static string ParentPath(BridgeContext ctx, Transform transform)
        {
            if (transform.parent == null || transform.parent == ctx.Target.transform)
            {
                return string.Empty;
            }
            return ctx.PathInTarget(transform.parent) + "/";
        }

        // By PREFIX. Renaming a socket also moves every light, pointer and
        // trigger hanging beneath it, and those are addressed by their own
        // longer paths.
        static int RewriteClips(BridgeContext ctx, Dictionary<string, string> remap)
        {
            int count = 0;
            foreach (var clip in Clips(ctx))
            {
                foreach (var binding in AnimationUtility.GetCurveBindings(clip))
                {
                    if (!Remap(binding.path, remap, out string path))
                    {
                        continue;
                    }
                    var curve = AnimationUtility.GetEditorCurve(clip, binding);
                    AnimationUtility.SetEditorCurve(clip, binding, null);
                    var moved = binding;
                    moved.path = path;
                    AnimationUtility.SetEditorCurve(clip, moved, curve);
                    count++;
                }

                // Material swaps and the like. A separate list, and losing
                // these is how a wardrobe half-applies.
                foreach (var binding in AnimationUtility.GetObjectReferenceCurveBindings(clip))
                {
                    if (!Remap(binding.path, remap, out string path))
                    {
                        continue;
                    }
                    var keys = AnimationUtility.GetObjectReferenceCurve(clip, binding);
                    AnimationUtility.SetObjectReferenceCurve(clip, binding, null);
                    var moved = binding;
                    moved.path = path;
                    AnimationUtility.SetObjectReferenceCurve(clip, moved, keys);
                    count++;
                }
            }
            return count;
        }

        // A layer mask that lists transforms lets the layer move only the
        // ones listed, by path. A listed path that no longer matches drops
        // that object's position and scale curves without a word.
        static void RewriteMasks(BridgeContext ctx, Dictionary<string, string> remap)
        {
            var seen = new HashSet<AvatarMask>();
            string controllerPath = AssetDatabase.GetAssetPath(ctx.MergedController);
            foreach (var layer in ctx.MergedController.layers)
            {
                var mask = layer?.avatarMask;
                if (mask == null || !seen.Add(mask))
                {
                    continue;
                }
                // Only masks this conversion owns. The self-container has
                // copied every foreign one by now, but a shared asset must
                // never be edited in place.
                string assetPath = AssetDatabase.GetAssetPath(mask);
                bool ours = string.IsNullOrEmpty(assetPath) || assetPath == controllerPath
                            || assetPath.StartsWith(ctx.OutputDir + "/", StringComparison.Ordinal);
                if (!ours)
                {
                    continue;
                }
                bool touched = false;
                for (int i = 0; i < mask.transformCount; i++)
                {
                    if (Remap(mask.GetTransformPath(i), remap, out string path))
                    {
                        mask.SetTransformPath(i, path);
                        touched = true;
                    }
                }
                if (touched)
                {
                    EditorUtility.SetDirty(mask);
                }
            }
        }

        static bool Remap(string path, Dictionary<string, string> remap, out string moved)
        {
            moved = null;
            if (string.IsNullOrEmpty(path))
            {
                return false;
            }
            // Longest key first: an object renamed inside another renamed
            // object must take its own new name, not only its parent's.
            foreach (var pair in remap.OrderByDescending(p => p.Key.Length))
            {
                if (path == pair.Key)
                {
                    moved = pair.Value;
                    return true;
                }
                // The separator matters: "A/Socket" must not match a
                // sibling called "A/SocketRing".
                if (path.StartsWith(pair.Key + "/"))
                {
                    moved = pair.Value + path.Substring(pair.Key.Length);
                    return true;
                }
            }
            return false;
        }

        static HashSet<string> AnimatedPaths(BridgeContext ctx)
        {
            var paths = new HashSet<string>();
            foreach (var clip in Clips(ctx))
            {
                foreach (var binding in AnimationUtility.GetCurveBindings(clip))
                {
                    paths.Add(binding.path);
                }
                foreach (var binding in AnimationUtility.GetObjectReferenceCurveBindings(clip))
                {
                    paths.Add(binding.path);
                }
            }
            return paths;
        }

        // Proves the rewrite was complete rather than assuming it. Counts
        // only paths naming a renamed object, so an avatar's own
        // pre-existing broken curves are not blamed on this pass.
        static List<string> Unresolved(BridgeContext ctx, HashSet<string> deadBefore)
        {
            var missing = new List<string>();
            foreach (string path in AnimatedPaths(ctx).OrderBy(p => p, StringComparer.Ordinal))
            {
                if (string.IsNullOrEmpty(path) || deadBefore.Contains(path))
                {
                    continue;
                }
                bool ours = Names.Any(n => path.Contains(n.To));
                // Resolved the way the animator resolves, not with Find:
                // the converted contact triggers under every socket are
                // named after their parameter, slashes and all, and Find
                // called all eighty-six of them dead while every one of
                // them worked in game.
                if (ours && BridgeContext.FindByAnimationPath(ctx.Target.transform, path) == null)
                {
                    missing.Add(path);
                }
            }
            return missing;
        }

        static IEnumerable<AnimationClip> Clips(BridgeContext ctx)
        {
            var seen = new HashSet<AnimationClip>();
            foreach (var clip in ctx.MergedController.animationClips)
            {
                if (clip != null && seen.Add(clip))
                {
                    yield return clip;
                }
            }
        }
    }
}
#endif
